!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  frame: ecef
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      frame: ecef
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
      x1: 743732.8125
      x2: 743848.5
      x3: 743922.0
      x4: 743797.0625
      y1: -5503834.0
      y2: -5503790.5
      y3: -5503827.0
      y4: -5503876.5
      z1: 3125611.0
      z2: 3125659.5
      z3: 3125578.5
      z4: 3125522.5
    state: []
  x1: 743732.8125
  x2: 743848.5
  x3: 743922.0
  x4: 743797.0625
  y1: -5503834.0
  y2: -5503790.5
  y3: -5503827.0
  y4: -5503876.5
  z1: 3125611.0
  z2: 3125659.5
  z3: 3125578.5
  z4: 3125522.5
state: []
