!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  frame: ecef
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      frame: ecef
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
      x1: -5507641.0
      x2: -5507722.0
      x3: -5507502.0
      x4: -5507382.0
      y1: -2237439.75
      y2: -2237666.25
      y3: -2237685.5
      y4: -2237428.25
      z1: 2303532.0
      z2: 2303470.75
      z3: 2303253.25
      z4: 2303296.25
    state: []
  x1: -5507641.0
  x2: -5507722.0
  x3: -5507502.0
  x4: -5507382.0
  y1: -2237439.75
  y2: -2237666.25
  y3: -2237685.5
  y4: -2237428.25
  z1: 2303532.0
  z2: 2303470.75
  z3: 2303253.25
  z4: 2303296.25
state: []
